[Unit]
Wants=qwensofia-account-display.service qwensofia-account-vnc.service qwensofia-account-websockify.service
After=qwensofia-account-display.service qwensofia-account-vnc.service qwensofia-account-websockify.service

[Service]
Environment=ACCOUNT_CREATOR_DISPLAY=:101
